### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by gmarokov** [gregoryb/trxtosonar#1]
Hi, can you provide a working example of parsing the params with real values?
Having a hard time to make it work unfortunately :/ 

Kind regards!

**Comment by gmarokov** [comment]
@yzhoholiev can you help me with that? I saw you have a recent fork?

**Comment by gregoryb** [comment]
Hello,

This command should do the job.
`./dotnet TrxToSonar.dll -p "C:\YourSolution\" -o "C:\YourSolution\Sonarqube.xml"`

**Comment by gmarokov** [comment]
Thank you! That did work :)
